### ISSUE TITLE
Outdated examples

### ISSUE THREAD

**Issue by enigma969** [caldav4j/caldav4j#78] opened 2018-07-13 10:31 UTC
Hi, 

first, big thanks for your work. But currently it's almost impossible to use the library since all examples are so outdated. Can you please update the examples or post some code where you've used the library? 

Thanks

Christian

**Comment by TheAntimist** [comment] 2018-07-13 11:01
Hello, Christian, thanks for the reporting. This is a work in progress, which I was supposed to complete earlier, but that didn't happen. Should hopefully happen as soon as #63 finishes, (or perhaps parallely) which should hopefully happen by next week. For now though, this is a duplicate of #66 , so I am closing it, but be sure that this is being added more and more.

**Closed by TheAntimist** 2018-07-13 11:01 UTC
