### ISSUE TITLE
updateEvent failure

### ISSUE THREAD

**Issue by mkneipl** [caldav4j/caldav4j#75] opened 2018-06-27 13:19 UTC
Hi,
When we are trying to update a Recurrence event via server call, its deleting the existing event completely.
Ideally, specified Calendar Date only to be deleted or modified to new Date(with same event ID).

**Comment by ioggstream** [comment] 2018-06-27 13:32
Hi @mkneipl ,

can you reproduce the issue? Please state:

  -   caldav4j version
  -   calendar server
  -   the expected REQUEST / RESPONSE
  -   the actual REQUEST / RESPONSE

If you could write and add testcase it would be easier to reproduce.

Thx++,
R.

**Comment by TheAntimist** [comment] 2018-07-12 16:55
@mkneipl Any further information is appreciated?

**Comment by TheAntimist** [comment] 2018-08-01 10:45
Closing issue due to no update. If the issue still persists, reopen the issue, if needed.

**Closed by TheAntimist** 2018-08-01 10:45 UTC
